In [1]:
# hanling null values
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r"D:\Internship_June2025\AllData\train.csv")
dataset

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,Owner,0,0,3,BHK,2500.000000,1,1,"Shamshabad Road,Agra",27.140626,78.043277,45.0
29447,Owner,0,0,2,BHK,769.230769,1,1,"E3-108, Lake View Recidency,,Vapi",39.945409,-86.150721,16.0
29448,Dealer,0,0,2,BHK,1022.641509,1,1,"Ajmer Road,Jaipur",26.928785,75.828002,27.1
29449,Owner,0,0,2,BHK,927.079009,1,1,"Sholinganallur,Chennai",12.900150,80.227910,67.0
29450,Dealer,0,1,2,BHK,896.774194,1,1,"Jagatpura,Jaipur",26.832353,75.841749,27.8

In [3]:
dataset.shape

(29451, 12)

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   POSTED_BY              29451 non-null  object
 1   UNDER_CONSTRUCTION     29451 non-null  int64
 2   RERA                   29451 non-null  int64
 3   BHK_NO.                29451 non-null  int64
 4   BHK_OR_RK              29451 non-null  object
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64
 7   RESALE                 29451 non-null  int64
 8   ADDRESS                29451 non-null  object
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), object(3)
memory usage: 2.7+ MB

In [5]:
dataset.isnull()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,False,False,False,False,False,False,False,False,False,False,False,False
29447,False,False,False,False,False,False,False,False,False,False,False,False
29448,False,False,False,False,False,False,False,False,False,False,False,False
29449,False,False,False,False,False,False,False,False,False,False,False,False
29450,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
dataset.notnull()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
29446,True,True,True,True,True,True,True,True,True,True,True,True
29447,True,True,True,True,True,True,True,True,True,True,True,True
29448,True,True,True,True,True,True,True,True,True,True,True,True
29449,True,True,True,True,True,True,True,True,True,True,True,True
29450,True,True,True,True,True,True,True,True,True,True,True,True

In [9]:
dataset.notnull().sum()

POSTED_BY                29451
UNDER_CONSTRUCTION       29451
RERA                     29451
BHK_NO.                  29451
BHK_OR_RK                29451
SQUARE_FT                29451
READY_TO_MOVE            29451
RESALE                   29451
ADDRESS                  29451
LONGITUDE                29451
LATITUDE                 29451
TARGET(PRICE_IN_LACS)    29451
dtype: int64

In [10]:
dataset.isnull().any()

POSTED_BY                False
UNDER_CONSTRUCTION       False
RERA                     False
BHK_NO.                  False
BHK_OR_RK                False
SQUARE_FT                False
READY_TO_MOVE            False
RESALE                   False
ADDRESS                  False
LONGITUDE                False
LATITUDE                 False
TARGET(PRICE_IN_LACS)    False
dtype: bool

In [6]:
dataset = pd.read_csv(r"D:\Internship_June2025\AllData\titanic.csv")
dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [12]:
dataset['age'] = dataset['age'].fillna(19)
dataset.head(25)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,19.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,19.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,19.0,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [13]:
m = dataset['age'].mean()
ab = np.round(m,2)
ab

np.float64(27.57)

In [14]:
dataset['age'] = dataset['age'].fillna(ab)
dataset.head(25)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,19.0,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
17,1,2,male,19.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
18,0,3,female,31.0,1,0,18.0000,S,Third,woman,False,NaN,Southampton,no,False
19,1,3,female,19.0,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
21,1,2,male,34.0,0,0,13.0000,S,Second,man,True,D,Southampton,yes,True
22,1,3,female,15.0,0,0,8.0292,Q,Third,child,False,NaN,Queenstown,yes,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,A,Southampton,yes,True
24,0,3,female,8.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [15]:
dataset['sex'] = dataset['sex'].replace('male','Purush')
dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,Purush,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,Purush,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,Purush,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,19.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,Purush,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,Purush,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [16]:
dataset['sex'] = dataset['sex'].replace('female','Mahila')
dataset

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,Purush,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,Mahila,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,Mahila,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,Mahila,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,Purush,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,Purush,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,Mahila,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,Mahila,19.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,Purush,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,Purush,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [17]:
for x in dataset['age']:
    print(x)

22.0
38.0
26.0
35.0
35.0
19.0
54.0
2.0
27.0
14.0
4.0
58.0
20.0
39.0
14.0
55.0
2.0
19.0
31.0
19.0
35.0
34.0
15.0
28.0
8.0
38.0
19.0
19.0
19.0
19.0
40.0
19.0
19.0
66.0
28.0
42.0
19.0
21.0
18.0
14.0
40.0
27.0
19.0
3.0
19.0
19.0
19.0
19.0
19.0
18.0
7.0
21.0
49.0
29.0
65.0
19.0
21.0
28.5
5.0
11.0
22.0
38.0
45.0
4.0
19.0
19.0
29.0
19.0
17.0
26.0
32.0
16.0
21.0
26.0
32.0
25.0
19.0
19.0
0.83
30.0
22.0
29.0
19.0
28.0
17.0
33.0
16.0
19.0
23.0
24.0
29.0
20.0
46.0
26.0
59.0
19.0
71.0
23.0
34.0
34.0
28.0
19.0
21.0
33.0
37.0
28.0
21.0
19.0
38.0
19.0
47.0
14.5
22.0
20.0
17.0
21.0
70.5
29.0
24.0
2.0
21.0
19.0
32.5
32.5
54.0
12.0
19.0
24.0
19.0
45.0
33.0
20.0
47.0
29.0
25.0
23.0
19.0
37.0
16.0
24.0
19.0
22.0
24.0
19.0
18.0
19.0
27.0
9.0
36.5
42.0
51.0
22.0
55.5
40.5
19.0
51.0
16.0
30.0
19.0
19.0
44.0
40.0
26.0
17.0
1.0
9.0
19.0
45.0
19.0
28.0
61.0
4.0
1.0
21.0
56.0
18.0
19.0
50.0
30.0
36.0
19.0
19.0
9.0
1.0
4.0
19.0
19.0
45.0
40.0
36.0
32.0
19.0
19.0
3.0
44.0
58.0
19.0
42.0
19.0
24.0
28.0
19.0
34.0
45.5
18.0
2.0
32.0
26.0
16.0
40.0
24.0
35.0
22.0
30.0
19.0
31.0
27.0
42.0
32.0
30.0
16.0
27.0
51.0
19.0
38.0
22.0
19.0
20.5
18.0
19.0
35.0
29.0
59.0
5.0
24.0
19.0
44.0
8.0
19.0
33.0
19.0
19.0
29.0
22.0
30.0
44.0
25.0
24.0
37.0
54.0
19.0
29.0
62.0
30.0
41.0
29.0
19.0
30.0
35.0
50.0
19.0
3.0
52.0
40.0
19.0
36.0
16.0
25.0
58.0
35.0
19.0
25.0
41.0
37.0
19.0
63.0
45.0
19.0
7.0
35.0
65.0
28.0
16.0
19.0
19.0
33.0
30.0
22.0
42.0
22.0
26.0
19.0
36.0
24.0
24.0
19.0
23.5
2.0
19.0
50.0
19.0
19.0
19.0
19.0
19.0
0.92
19.0
17.0
30.0
30.0
24.0
18.0
26.0
28.0
43.0
26.0
24.0
54.0
31.0
40.0
22.0
27.0
30.0
22.0
19.0
36.0
61.0
36.0
31.0
16.0
19.0
45.5
38.0
16.0
19.0
19.0
29.0
41.0
45.0
45.0
2.0
24.0
28.0
25.0
36.0
24.0
40.0
19.0
3.0
42.0
23.0
19.0
15.0
25.0
19.0
28.0
22.0
38.0
19.0
19.0
40.0
29.0
45.0
35.0
19.0
30.0
60.0
19.0
19.0
24.0
25.0
18.0
19.0
22.0
3.0
19.0
22.0
27.0
20.0
19.0
42.0
1.0
32.0
35.0
19.0
18.0
1.0
36.0
19.0
17.0
36.0
21.0
28.0
23.0
24.0
22.0
31.0
46.0
23.0
28.0
39.0
26.0
21.0
28.0
20.0
34.0
51.0
3.0
21.0
19.0
19.0
19.0
33.0
19.0
44.0
19.0
34.0
18.0
30.0
10.0
19.0
21.0
29.0
28.0
18.0
19.0
28.0
19.0
19.0
32.0
28.0
19.0
42.0
17.0
50.0
14.0
21.0
24.0
64.0
31.0
45.0
20.0
25.0
28.0
19.0
4.0
13.0
34.0
5.0
52.0
36.0
19.0
30.0
49.0
19.0
29.0
65.0
19.0
50.0
19.0
48.0
34.0
47.0
48.0
19.0
38.0
19.0
56.0
19.0
0.75
19.0
38.0
33.0
23.0
22.0
19.0
34.0
29.0
22.0
2.0
9.0
19.0
50.0
63.0
25.0
19.0
35.0
58.0
30.0
9.0
19.0
21.0
55.0
71.0
21.0
19.0
54.0
19.0
25.0
24.0
17.0
21.0
19.0
37.0
16.0
18.0
33.0
19.0
28.0
26.0
29.0
19.0
36.0
54.0
24.0
47.0
34.0
19.0
36.0
32.0
30.0
22.0
19.0
44.0
19.0
40.5
50.0
19.0
39.0
23.0
2.0
19.0
17.0
19.0
30.0
7.0
45.0
30.0
19.0
22.0
36.0
9.0
11.0
32.0
50.0
64.0
19.0
19.0
33.0
8.0
17.0
27.0
19.0
22.0
22.0
62.0
48.0
19.0
39.0
36.0
19.0
40.0
28.0
19.0
19.0
24.0
19.0
29.0
19.0
32.0
62.0
53.0
36.0
19.0
16.0
19.0
34.0
39.0
19.0
32.0
25.0
39.0
54.0
36.0
19.0
18.0
47.0
60.0
22.0
19.0
35.0
52.0
47.0
19.0
37.0
36.0
19.0
49.0
19.0
49.0
24.0
19.0
19.0
44.0
35.0
36.0
30.0
27.0
22.0
40.0
39.0
19.0
19.0
19.0
35.0
24.0
34.0
26.0
4.0
26.0
27.0
42.0
20.0
21.0
21.0
61.0
57.0
21.0
26.0
19.0
80.0
51.0
32.0
19.0
9.0
28.0
32.0
31.0
41.0
19.0
20.0
24.0
2.0
19.0
0.75
48.0
19.0
56.0
19.0
23.0
19.0
18.0
21.0
19.0
18.0
24.0
19.0
32.0
23.0
58.0
50.0
40.0
47.0
36.0
20.0
32.0
25.0
19.0
43.0
19.0
40.0
31.0
70.0
31.0
19.0
18.0
24.5
18.0
43.0
36.0
19.0
27.0
20.0
14.0
60.0
25.0
14.0
19.0
18.0
15.0
31.0
4.0
19.0
25.0
60.0
52.0
44.0
19.0
49.0
42.0
18.0
35.0
18.0
25.0
26.0
39.0
45.0
42.0
22.0
19.0
24.0
19.0
48.0
29.0
52.0
19.0
38.0
27.0
19.0
33.0
6.0
17.0
34.0
50.0
27.0
20.0
30.0
19.0
25.0
25.0
29.0
11.0
19.0
23.0
23.0
28.5
48.0
35.0
19.0
19.0
19.0
36.0
21.0
24.0
31.0
70.0
16.0
30.0
19.0
31.0
4.0
6.0
33.0
23.0
48.0
0.67
28.0
18.0
34.0
33.0
19.0
41.0
20.0
36.0
16.0
51.0
19.0
30.5
19.0
32.0
24.0
48.0
57.0
19.0
54.0
18.0
19.0
5.0
19.0
43.0
13.0
17.0
29.0
19.0
25.0
25.0
18.0
8.0
1.0
46.0
19.0
16.0
19.0
19.0
25.0
39.0
49.0
31.0
30.0
30.0
34.0
31.0
11.0
0.42
27.0
31.0
39.0
18.0
39.0
33.0
26.0
39.0
35.0
6.0
30.5
19.0
23.0
31.0
43.0
10.0
52.0
27.0
38.0
27.0
2.0
19.0
19.0
1.0
19.0
62.0
15.0
0.83
19.0
23.0
18.0
39.0
21.0
19.0
32.0
19.0
20.0
16.0
30.0
34.5
17.0
42.0
19.0
35.0
28.0
19.0
4.0
74.0
9.0
16.0
44.0
18.0
45.0
51.0
24.0
19.0
41.0
21.0
48.0
19.0
24.0
42.0
27.0
31.0
19.0
4.0
26.0
47.0
33.0
47.0
28.0
15.0
20.0
19.0
19.0
56.0
25.0
33.0
22.0
28.0
25.0
39.0
27.0
19.0
19.0
26.0
32.0

In [7]:
india_weather = pd.DataFrame({
    "city":['newyork','chicago','orlando'],
    'temperature':[32,45,30],
    "humidity":[80,60,78]
})
india_weather

       city  temperature  humidity
0    mumbai           32        80
1     delhi           45        60
2  benglore           30        78

In [9]:
usa_weather = pd.DataFrame({
    "city":['newyork','chicago','orlando'],
    'temperature':[32,45,30],
    "humidity":[80,60,78]
})
usa_weather

      city  temperature  humidity
0  newyork           32        80
1  chicago           45        60
2  orlando           30        78

In [ ]:
df = pd.concat([

In [10]:
windspeed_df = pd.DataFrame({
    "city":['mumbai','delhi'],
    "humidity":[80,60]
},index=[1,0])
windspeed_df

     city  humidity
1  mumbai        80
0   delhi        60

In [11]:
df1 = pd.DataFrame({
    "city":['newyork','chicago','orlando'],
    'temperature':[32,45,30],
})
df1

      city  temperature
0  newyork           32
1  chicago           45
2  orlando           30

In [12]:
df2 = pd.DataFrame({
    "city":['newyork','chicago','orlando'],
    'humidity':[32,45,30],
})
df2

      city  humidity
0  newyork        32
1  chicago        45
2  orlando        30

In [13]:
df3 = pd.merge(df1,df2, on="city")
df3

      city  temperature  humidity
0  newyork           32        32
1  chicago           45        45
2  orlando           30        30

In [14]:
df1 = pd.DataFrame({
    "city":['newyork','chicago','orlando','baltimore'],
    'temperature':[32,45,30,38],
})
df1

        city  temperature
0    newyork           32
1    chicago           45
2    orlando           30
3  baltimore           38

In [15]:
df2 = pd.DataFrame({
    "city":['newyork','chicago','san diego'],
    'humidity':[32,45,30],
})
df2

        city  humidity
0    newyork        32
1    chicago        45
2  san diego        30

In [16]:
df3 = pd.merge(df1,df2, on="city",how="inner")
df3

      city  temperature  humidity
0  newyork           32        32
1  chicago           45        45

In [17]:
df3 = pd.merge(df1,df2, on="city",how="outer")
df3

        city  temperature  humidity
0  baltimore         38.0       NaN
1    chicago         45.0      45.0
2    newyork         32.0      32.0
3    orlando         30.0       NaN
4  san diego          NaN      30.0

In [18]:
df3 = pd.merge(df1,df2, on="city",how="left")
df3

        city  temperature  humidity
0    newyork           32      32.0
1    chicago           45      45.0
2    orlando           30       NaN
3  baltimore           38       NaN